% NM algorithm for solving for the simultaneous process.
function val = simultaneous_objective_function(...
                                lambda_model,...
                                param)
% This function will be anonymized and used as an argument to fminsearch
% param is a constant structure for each run of fminsearch.

% Obtain probabilities q on decision problem data which is then fed to wTRP solver.
q = get_predicted_probabilities(param.unLabeled,...
                                param.n_features, ...
                                lambda_model, ...
                                param.cost_model_type);

% Compute route
[~,optimal_route_cost] = solve_wTRP(param.C,q,[],[]); %todo: exception handling

%compute the objective value for the given route and linear model
val = param.C0*sum(log(1+(exp(-(param.X*lambda_model).*param.Y))))/length(param.Y) ...
        + param.C1*optimal_route_cost ...
        + param.C2*norm(lambda_model)^2;