function [param0] = get_initial_parameters()



param0.seed = RandStream('mcg16807','Seed',0); RandStream.setGlobalStream(param0.seed); 
param0.result_path            = './';%'/Users/theja/Downloads/temp/mloc_results_feb_2014/';
param0.str_addendum           = '';
param0.n_sample_size_pcts     = [0.1];%[.1:.1:1];
param0.n_multirun             = 2;%100; %loop through n_multirun autogenerated decisions if ~=1 else do single exp.
param0.decision_nodes         = 7; %number of nodes in the decision problem.
param0.n_bad_instances      = 0;
param0.cost_model_type      = 2; % 1 and 2 vary the way predictions are used in wTRP objective.
param0.C2_coeff_range       = [0.01];% [0.01 0.025 0.05 0.075];%l2 regularization coefficient range, default reg param may be bad. see cvalidated.m
param0.n_folds              = 2;%5;
param0.n_repeats            = 1;%3;
param0.C0                   = 1000;
param0.fminsearch_opts      = optimset('display','off','TolFun',1e-4,...
                                'MaxIter', 500,'MaxFunEvals',1000,...
                                'TolX',1e-4); 
param0.am_maximum_iterations= 25;
param0.am_tolerance         = 10^-4;
if (param0.cost_model_type==1)
    param0.C1array = 0.001;%0.001*[.5 1 3 5];  %for 7 node data for cost type 1.
else
    param0.C1array = 0.001;%0.001*[.1 .5 1 5]; %for 7 node data and cost type 2.
end